DROP DATABASE adaptDB;
CREATE DATABASE adaptDB;
DROP TABLE adaptDB.choices;
CREATE TABLE adaptDB.choices (chioce_id int NOT NULL AUTO_INCREMENT, name varchar(255), value varchar(255), elements_id int NOT NULL, PRIMARY KEY (chioce_id), INDEX elements_id_idx (elements_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.elements;
CREATE TABLE adaptDB.elements (elements_id int NOT NULL AUTO_INCREMENT, startWithNewLine tinyint, hasOther tinyint, name varchar(255) NOT NULL, visibleIf varchar(255), type varchar(255) NOT NULL, title varchar(500), titleLocation varchar(45), colCount int, description longtext, inputType varchar(255), otherText varchar(255), popupdescription blob, page_id int NOT NULL, questionnaires_id int NOT NULL, PRIMARY KEY (name, questionnaires_id), INDEX elements_id (elements_id), INDEX page_id_idx (elements_id, page_id), INDEX page_id_idx1 (page_id), INDEX questionnaires_id_idx (questionnaires_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.pages;
CREATE TABLE adaptDB.pages (page_id int NOT NULL AUTO_INCREMENT, name varchar(255) NOT NULL, title varchar(255), questionnaires_id int NOT NULL, PRIMARY KEY (name, questionnaires_id), CONSTRAINT name_UNIQUE UNIQUE (name), INDEX questionnaires_id_idx (questionnaires_id), INDEX page_id (page_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.participant_study;
CREATE TABLE adaptDB.participant_study (participant_study_id int NOT NULL AUTO_INCREMENT, participant_id int NOT NULL, study_information longtext, timeline varchar(255), study_id int, status varchar(255), completed_time timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL, PRIMARY KEY (participant_study_id), INDEX participant_study_FK_1 (study_id), INDEX participant_study_FK_2 (participant_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.participants;
CREATE TABLE adaptDB.participants (participant_id int NOT NULL AUTO_INCREMENT, autotime timestamp DEFAULT CURRENT_TIMESTAMP, logid varchar(15), loghost varchar(20), first_name varchar(255) NOT NULL, last_name varchar(255) NOT NULL, naccID varchar(45) NOT NULL, gender varchar(45) NOT NULL, race varchar(255) NOT NULL, ethnicity varchar(255) NOT NULL, dob varchar(45) NOT NULL, ques1 varchar(45) NOT NULL, ques2 varchar(45) NOT NULL, ques3 varchar(45) NOT NULL, ques4 varchar(45) NOT NULL, autolog timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, revlogid varchar(15), revloghost varchar(40), PRIMARY KEY (participant_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.questionnaire;
CREATE TABLE adaptDB.questionnaire (questionnaire_id int NOT NULL AUTO_INCREMENT, questionnaire_type varchar(45), questions longtext, PRIMARY KEY (questionnaire_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adapt.questionnaire_sequence;
CREATE TABLE adaptDB.questionnaire_sequence (questionnaire_sequence_id binary(16) NOT NULL, question_id binary(16), answer varchar(255), next_question_id binary(16), PRIMARY KEY (questionnaire_sequence_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.questionnaires;
CREATE TABLE adaptDB.questionnaires (questionnaires_id int NOT NULL AUTO_INCREMENT, showProgressBar varchar(45), showPageTitles tinyint, showQuestionNumbers varchar(45), completedHtml blob, title varchar(500), question_type varchar(255) NOT NULL, PRIMARY KEY (questionnaires_id), CONSTRAINT question_type_UNIQUE UNIQUE (question_type)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.study;
CREATE TABLE adaptDB.study (study_id int NOT NULL, study_name varchar(255), PRIMARY KEY (study_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1001, ''Vascular Risk'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1002, ''Sleep Study'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1003, ''Everyday Cognition (E-Cog)'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1004, ''Diet Screening'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1005, ''Physical Activity Screening'');
DROP TABLE adaptDB.webroles;
CREATE TABLE adaptDB.webroles (username varchar(100) NOT NULL, rolename varchar(20) NOT NULL, PRIMARY KEY (username, rolename)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.webusers;
CREATE TABLE adaptDB.webusers (id int(10) unsigned NOT NULL AUTO_INCREMENT, tprefix varchar(5), fname varchar(20), lname varchar(20), tsuffix varchar(5), username varchar(100) NOT NULL, userpass varchar(15), wphone varchar(16), email varchar(100), site varchar(100), active varchar(1) DEFAULT ''Y'', hostname varchar(50), PRIMARY KEY (username), CONSTRAINT rowno UNIQUE (id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
ALTER TABLE adaptDB.elements ADD CONSTRAINT elements_fk2 FOREIGN KEY (`questionnaires_id`) REFERENCES adaptDB.questionnaires (`questionnaires_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE adaptDB.elements ADD CONSTRAINT page_id FOREIGN KEY (`page_id`) REFERENCES adaptDB.pages (`page_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE adaptDB.pages ADD CONSTRAINT questionnaires_id FOREIGN KEY (`questionnaires_id`) REFERENCES adaptDB.questionnaires (`questionnaires_id`);
ALTER TABLE adaptDB.participant_study ADD CONSTRAINT participant_study_FK_1 FOREIGN KEY (`study_id`) REFERENCES adaptDB.study (`study_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE adaptDB.participant_study ADD CONSTRAINT participant_study_FK_2 FOREIGN KEY (`participant_id`) REFERENCES adaptDB.participants (`participant_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE adaptDB.webroles ADD CONSTRAINT webroles_FK_1 FOREIGN KEY (`username`) REFERENCES adaptDB.webusers (`username`) ON DELETE CASCADE ON UPDATE CASCADE;
