DROP DATABASE adaptDB;
CREATE DATABASE adaptDB;
DROP TABLE adaptDB.choices;
CREATE TABLE adaptDB.choices (chioce_id int NOT NULL AUTO_INCREMENT, name varchar(255), value varchar(255), elements_id int NOT NULL, PRIMARY KEY (chioce_id), INDEX elements_id_idx (elements_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.elements;
CREATE TABLE adaptDB.elements (elements_id int NOT NULL AUTO_INCREMENT, startWithNewLine tinyint, hasOther tinyint, name varchar(255) NOT NULL, visibleIf varchar(255), type varchar(255) NOT NULL, title varchar(500), titleLocation varchar(45), colCount int, description longtext, inputType varchar(255), otherText varchar(255), popupdescription blob, page_id int NOT NULL, questionnaires_id int NOT NULL, PRIMARY KEY (name, questionnaires_id), INDEX elements_id (elements_id), INDEX page_id_idx (elements_id, page_id), INDEX page_id_idx1 (page_id), INDEX questionnaires_id_idx (questionnaires_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.pages;
CREATE TABLE adaptDB.pages (page_id int NOT NULL AUTO_INCREMENT, name varchar(255) NOT NULL, title varchar(255), questionnaires_id int NOT NULL, PRIMARY KEY (name, questionnaires_id), CONSTRAINT name_UNIQUE UNIQUE (name), INDEX questionnaires_id_idx (questionnaires_id), INDEX page_id (page_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.participant_study;
CREATE TABLE adaptDB.participant_study (participant_study_id int NOT NULL AUTO_INCREMENT, participant_id int NOT NULL, study_information longtext, timeline varchar(255), study_id int, status varchar(255), completed_time timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NULL, PRIMARY KEY (participant_study_id), INDEX participant_study_FK_1 (study_id), INDEX participant_study_FK_2 (participant_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.participants;
CREATE TABLE adaptDB.participants (participant_id int NOT NULL AUTO_INCREMENT, autotime timestamp DEFAULT CURRENT_TIMESTAMP, logid varchar(15), loghost varchar(20), first_name varchar(255) NOT NULL, last_name varchar(255) NOT NULL, naccID varchar(45) NOT NULL, gender varchar(45) NOT NULL, race varchar(255) NOT NULL, ethnicity varchar(255) NOT NULL, dob varchar(45) NOT NULL, ques1 varchar(45) NOT NULL, ques2 varchar(45) NOT NULL, ques3 varchar(45) NOT NULL, ques4 varchar(45) NOT NULL, autolog timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, revlogid varchar(15), revloghost varchar(40), PRIMARY KEY (participant_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.questionnaire;
CREATE TABLE adaptDB.questionnaire (questionnaire_id int NOT NULL AUTO_INCREMENT, questionnaire_type varchar(45), questions longtext, PRIMARY KEY (questionnaire_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adapt.questionnaire_sequence;
CREATE TABLE adaptDB.questionnaire_sequence (questionnaire_sequence_id binary(16) NOT NULL, question_id binary(16), answer varchar(255), next_question_id binary(16), PRIMARY KEY (questionnaire_sequence_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.questionnaires;
CREATE TABLE adaptDB.questionnaires (questionnaires_id int NOT NULL AUTO_INCREMENT, showProgressBar varchar(45), showPageTitles tinyint, showQuestionNumbers varchar(45), completedHtml blob, title varchar(500), question_type varchar(255) NOT NULL, PRIMARY KEY (questionnaires_id), CONSTRAINT question_type_UNIQUE UNIQUE (question_type)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.study;
CREATE TABLE adaptDB.study (study_id int NOT NULL, study_name varchar(255), PRIMARY KEY (study_id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1001, ''Vascular Risk'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1002, ''Sleep Study'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1003, ''Everyday Cognition (E-Cog)'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1004, ''Diet Screening'');
INSERT INTO adaptDB.study (study_id, study_name) VALUES (1005, ''Physical Activity Screening'');
DROP TABLE adaptDB.webroles;
CREATE TABLE adaptDB.webroles (username varchar(100) NOT NULL, rolename varchar(20) NOT NULL, PRIMARY KEY (username, rolename)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
DROP TABLE adaptDB.webusers;
CREATE TABLE adaptDB.webusers (id int(10) unsigned NOT NULL AUTO_INCREMENT, tprefix varchar(5), fname varchar(20), lname varchar(20), tsuffix varchar(5), username varchar(100) NOT NULL, userpass varchar(15), wphone varchar(16), email varchar(100), site varchar(100), active varchar(1) DEFAULT ''Y'', hostname varchar(50), PRIMARY KEY (username), CONSTRAINT rowno UNIQUE (id)) ENGINE=InnoDB DEFAULT CHARSET=latin1 DEFAULT COLLATE=latin1_swedish_ci;
ALTER TABLE adaptDB.elements ADD CONSTRAINT elements_fk2 FOREIGN KEY (`questionnaires_id`) REFERENCES adaptDB.questionnaires (`questionnaires_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE adaptDB.elements ADD CONSTRAINT page_id FOREIGN KEY (`page_id`) REFERENCES adaptDB.pages (`page_id`) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE adaptDB.pages ADD CONSTRAINT questionnaires_id FOREIGN KEY (`questionnaires_id`) REFERENCES adaptDB.questionnaires (`questionnaires_id`);
ALTER TABLE adaptDB.participant_study ADD CONSTRAINT participant_study_FK_1 FOREIGN KEY (`study_id`) REFERENCES adaptDB.study (`study_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE adaptDB.participant_study ADD CONSTRAINT participant_study_FK_2 FOREIGN KEY (`participant_id`) REFERENCES adaptDB.participants (`participant_id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE adaptDB.webroles ADD CONSTRAINT webroles_FK_1 FOREIGN KEY (`username`) REFERENCES adaptDB.webusers (`username`) ON DELETE CASCADE ON UPDATE CASCADE;
DROP TABLE adaptDB.medicine_list;
CREATE TABLE adaptDB.medicine_list (
  `medicine_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`medicine_id`)
) ENGINE=InnoDB AUTO_INCREMENT=303 DEFAULT CHARSET=latin1;
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (1, 'Acarbose');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (2, 'Accupril');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (3, 'Acebutolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (4, 'Aceon');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (5, 'Acetazolamide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (6, 'Actos');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (7, 'Adalat');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (8, 'Aldactazide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (9, 'Aldactone');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (10, 'Aldomet');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (11, 'Aldoril');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (12, 'Altace');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (13, 'Amaryl');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (14, 'Amiloride + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (15, 'Amiloride hydrochloride ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (16, 'Amlodipine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (17, 'Amlodipine + benazepril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (18, 'Antara');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (19, 'Apresazide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (20, 'Apresoline');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (21, 'Aranesp');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (22, 'Aspirin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (23, 'Atacand');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (24, 'Atenolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (25, 'Atenolol + chlorthalidone ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (26, 'atorvastatin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (27, 'Avandia');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (28, 'Avapro');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (29, 'Benazepril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (30, 'Benazepril + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (31, 'Bepridil ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (32, 'Betapace');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (33, 'Betaxolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (34, 'Bisoprolol + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (35, 'Bisoprolol/hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (36, 'Blocadren');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (37, 'Bumetanide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (38, 'Bumex');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (39, 'Byetta');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (40, 'Caduet');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (41, 'Calan');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (42, 'Calcitriol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (43, 'Calcium Carbonate');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (44, 'Caltrate');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (45, 'Candesartan ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (46, 'Capoten');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (47, 'Capozide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (48, 'Captopril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (49, 'Captopril + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (50, 'Cardene');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (51, 'Cardizem');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (52, 'Cardura');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (53, 'Carteolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (54, 'Cartrol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (55, 'Carvedilol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (56, 'Catapres');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (57, 'Chlorothiazide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (58, 'Chlorthalidone ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (59, 'cholestyramine');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (60, 'Clonidine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (61, 'Clopidogrel');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (62, 'Clorpres');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (63, 'colesevelam');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (64, 'Colestid');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (65, 'colestipol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (66, 'Coreg');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (67, 'Corgard');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (68, 'Corzide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (69, 'Coumadin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (70, 'Covera');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (71, 'Cozaar');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (72, 'Crestor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (73, 'Dalteparin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (74, 'Danaparoid');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (75, 'darbepoetin alfa');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (76, 'Demadex');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (77, 'Dexferrum');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (78, 'DiaBeta');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (79, 'Diamox');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (80, 'Digoxin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (81, 'Dilacor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (82, 'Diltiazem ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (83, 'Diovan');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (84, 'Dipyridamole');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (85, 'Diruil');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (86, 'Doxazosin ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (87, 'Dyazide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (88, 'DynaCirc');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (89, 'Dyrenium');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (90, 'Edecrin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (91, 'Enalapril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (92, 'Enalapril + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (93, 'Enoxaparin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (94, 'epoetin alfa');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (95, 'epoetin beta-methoxy polyethylene glycol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (96, 'Epogen');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (97, 'Eprosartan ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (98, 'Esidrix');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (99, 'Estrostep Fe');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (100, 'Ethacrynic acid ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (101, 'Exenatide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (102, 'ezetimibe');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (103, 'ezetimibe + simvastatin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (104, 'Felodipine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (105, 'Felodipine + enalapril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (106, 'fenofibrate');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (107, 'Feraheme');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (108, 'Fergon');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (109, 'Ferralet');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (110, 'Ferrlecit');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (111, 'ferrous gluconate');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (112, 'ferumoxytol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (113, 'fluvastatin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (114, 'Fortamet');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (115, 'Fosinopril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (116, 'Fragmin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (117, 'Furosemide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (118, 'gemfibrozil');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (119, 'Glimepiride');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (120, 'Glipizide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (121, 'Glucophage');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (122, 'Glucotrol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (123, 'Glyburide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (124, 'Glynase');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (125, 'Glyset');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (126, 'Guanabenz ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (127, 'Guanfacine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (128, 'heme iron polypeptide/folic acid');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (129, 'Heparin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (130, 'Hydralazine');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (131, 'Hydralazine + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (132, 'Hydralazine hydrochloride ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (133, 'Hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (134, 'HydroDiuril');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (135, 'Hytrin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (136, 'Hyzaar');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (137, 'Imferon');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (138, 'Indapamide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (139, 'Inderal');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (140, 'Inderal LA');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (141, 'Inderide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (142, 'INFeD');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (143, 'Innohep');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (144, 'Irbesartan ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (145, 'iron dextran');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (146, 'Isoptin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (147, 'Isordil');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (148, 'Isosorbide dinitrate');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (149, 'Isradipine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (150, 'Januvia');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (151, 'Kerlone');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (152, 'Labetalol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (153, 'Lanoxin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (154, 'Lanozicaps ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (155, 'Lasix');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (156, 'Lescol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (157, 'Levatol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (158, 'Lexxel');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (159, 'Linagliptin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (160, 'Lipitor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (161, 'Liraglutide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (162, 'Lisinopril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (163, 'Lisinopril + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (164, 'Livalo');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (165, 'Loestrin Fe');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (166, 'Lopid');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (167, 'Lopressor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (168, 'Lopressor HCT');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (169, 'Losartan ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (170, 'Losartan + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (171, 'Lotensin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (172, 'Lotensin HCT');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (173, 'Lotrel');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (174, 'lovastatin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (175, 'Lovenox');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (176, 'Lozol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (177, 'Mavik');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (178, 'Maxide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (179, 'Metformin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (180, 'Methyldopa ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (181, 'Methyldopa + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (182, 'Metolazone ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (183, 'Metoprolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (184, 'Metoprolol + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (185, 'Mevacor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (186, 'Micardis');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (187, 'Microzide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (188, 'Midamor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (189, 'Miglitol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (190, 'Minipress');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (191, 'Mircera');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (192, 'Moduretic');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (193, 'Moexipril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (194, 'Monopril');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (195, 'Mykrox');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (196, 'Nadolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (197, 'Nadolol + bendroflumethiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (198, 'Nateglinide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (199, 'Natrecor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (200, 'Nesiritide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (201, 'Niaspan');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (202, 'Nicardipine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (203, 'nicotinic acid');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (204, 'Nifedipine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (205, 'Nimodipine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (206, 'Nimotop');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (207, 'Nisoldipine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (208, 'Nitrates');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (209, 'Nitroglycerin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (210, 'Norethindrone Ethinyl Estradiol Ferrous Fumarate/sulfate');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (211, 'Normodyne');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (212, 'Norvasc');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (213, 'Omontys');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (214, 'Onglyza');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (215, 'Orgaran');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (216, 'peginesatide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (217, 'Penbutolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (218, 'Perindopril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (219, 'Persantine');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (220, 'Pioglitazone');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (221, 'pitavastatin ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (222, 'Plavix');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (223, 'Plendil');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (224, 'Pramlintide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (225, 'Prandin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (226, 'Pravachol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (227, 'pravastatin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (228, 'Prazosin ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (229, 'Precose');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (230, 'Prinivil');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (231, 'Prinzide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (232, 'Procardia XL');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (233, 'Procrit');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (234, 'Proferrin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (235, 'Proferrin-Forte');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (236, 'Propranolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (237, 'Propranolol + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (238, 'Questran');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (239, 'Quinapril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (240, 'Ramipril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (241, 'Renagel ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (242, 'Renvela');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (243, 'Repaglinide');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (244, 'Reserpine ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (245, 'Rocaltrol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (246, 'Rosiglitazone');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (247, 'rosuvastatin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (248, 'Saxagliptin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (249, 'Sectral');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (250, 'Serpasil');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (251, 'Sevelamer');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (252, 'Simron');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (253, 'simvastatin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (254, 'Sitagliptin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (255, 'sodium ferric gluconate complex');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (256, 'Sotalol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (257, 'Spironolactone ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (258, 'Spironolactone + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (259, 'Starlix');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (260, 'Sular');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (261, 'Symlin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (262, 'Tarka');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (263, 'Telmisartan ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (264, 'Tenex');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (265, 'Tenoretic');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (266, 'Tenormin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (267, 'Terazosin ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (268, 'Teveten');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (269, 'Thalidone');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (270, 'Tiazac');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (271, 'Ticlid');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (272, 'Ticlopidine');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (273, 'Timolol ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (274, 'Tinzaparin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (275, 'Toprol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (276, 'Torsemide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (277, 'Tradjenta');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (278, 'Trandate');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (279, 'Trandolapril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (280, 'Triamterene ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (281, 'Triamterene + hydrochlorothiazide ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (282, 'Univasc');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (283, 'Valsartan ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (284, 'Vascor');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (285, 'Vaseretic');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (286, 'Vasotec');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (287, 'Verapamil extended release + trandolapril ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (288, 'Verapamil hydrochloride ');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (289, 'Verelan');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (290, 'Victoza');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (291, 'Vytorin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (292, 'Warfarin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (293, 'Welchol');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (294, 'Wytensin');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (295, 'Zaroxolyn');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (296, 'Zebeta');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (297, 'Zestoretic');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (298, 'Zestril');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (299, 'Zetia');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (300, 'Ziac');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (301, 'Ziac');
INSERT INTO adaptDB.medicine_list (medicine_id, name) VALUES (302, 'Zocor');
DROP TABLE adaptDB.cereal_list;
CREATE TABLE adaptDB.cereal_list (
  `cereal_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(300) DEFAULT NULL,
  PRIMARY KEY (`cereal_id`)
) ENGINE=InnoDB AUTO_INCREMENT=325 DEFAULT CHARSET=latin1;
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (1, '100% Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (2, '100% Low Fat Natural Granola');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (3, '100% Natural Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (4, '100% Natural Cereal, with oats, honey and raisins');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (5, '100% Natural Granola, Oats & Honey');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (6, '100% Natural Wholegrain Cereal with raisins, lowfat');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (7, 'All-Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (8, 'All-Bran Bran Buds');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (9, 'All-Bran with Extra Fiber');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (10, 'Alpen');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (11, 'Alpha-Bits');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (12, 'Alpha-Bits with marshmallows');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (13, 'Amaranth Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (14, 'Apple Jacks');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (15, 'Apple Zaps');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (16, 'Apple Zings, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (17, 'Banana Nut Crunch Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (18, 'Barley');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (19, 'Basic 4');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (20, 'Berry Colossal Crunch, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (21, 'Blueberry Morning');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (22, 'Booberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (23, 'Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (24, 'Bran Buds');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (25, 'Bran flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (26, 'Bran, Nabisco');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (27, 'Branola');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (28, 'Brown Sugar Bliss');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (29, 'Buckwheat groats');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (30, 'Bulgur');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (31, 'Cap''n Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (32, 'Cap''n Crunch''s Christmas Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (33, 'Cap''n Crunch''s Crunch Berries');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (34, 'Cap''n Crunch''s Oops! ChocoDonuts');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (35, 'Cap''n Crunch''s Peanut Butter Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (36, 'Cheerios');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (37, 'Cheerios, Apple Cinnamon');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (38, 'Cheerios, Berry Burst');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (39, 'Cheerios, Berry Burst Strawberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (40, 'Cheerios, Berry Burst Triple Berry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (41, 'Cheerios, Berry Burst, Cherry Vanilla');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (42, 'Cheerios, Berry Burst, Strawberry Banana');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (43, 'Cheerios, Frosted');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (44, 'Cheerios, Honey Nut');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (45, 'Cheerios, Multi Grain');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (46, 'Cheerios, Team');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (47, 'Cheerios, Yogurt Burst, Strawberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (48, 'Cheerios, Yogurt Burst, Vanilla');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (49, 'Cheese grits');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (50, 'Chex');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (51, 'Chex Morning Mix Banana Nut');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (52, 'Chex Morning Mix Cinnamon');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (53, 'Chex Morning Mix Fruit & Nut');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (54, 'Chex Morning Mix Honey Nut');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (55, 'Chex, Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (56, 'Chex, Corn');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (57, 'Chex, Honey Nut');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (58, 'Chex, Multi-Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (59, 'Chex, Rice');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (60, 'Chex, Wheat');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (61, 'Chocolate frosted cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (62, 'Cinnamon Cluster Raisin Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (63, 'Cinnamon Crunch Crispix');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (64, 'Cinnamon Grahams Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (65, 'Cinnamon Marshmallow Scooby Doo!');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (66, 'Cinnamon Toast Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (67, 'Cinnamon Toast Crunch, Reduced Sugar');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (68, 'Coco-Roos, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (69, 'Cocoa Blasts');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (70, 'Cocoa Comets');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (71, 'Cocoa Dyno Bites, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (72, 'Cocoa Krispies');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (73, 'Cocoa Pebbles');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (74, 'Cocoa Puffs');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (75, 'Cocoa Puffs, Reduced Sugar');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (76, 'Cocoa Wheats');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (77, 'Complete Bran Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (78, 'Complete Oat Bran Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (79, 'Complete Wheat Bran Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (80, 'Cookie-Crisp (all flavors)');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (81, 'Corn Bursts, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (82, 'Corn Flakes, Kellogg''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (83, 'Corn Pops');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (84, 'Corn Puffs');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (85, 'Corn flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (86, 'Corn flakes, low sodium');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (87, 'Cornmeal mush');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (88, 'Count Chocula');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (89, 'Cracklin'' Oat Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (90, 'Cranberry Almond Crunch Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (91, 'Cream of Rice');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (92, 'Cream of Rye');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (93, 'Cream of Wheat');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (94, 'Crisp Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (95, 'Crispix');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (96, 'Crispy Brown Rice Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (97, 'Crispy Rice');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (98, 'Crispy Rice, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (99, 'Crispy Wheats''N Raisins');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (100, 'Crunchy Corn Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (101, 'Disney Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (102, 'Disney Hunny B''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (103, 'Disney Mickey''s Magix');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (104, 'Disney Mud & Bugs');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (105, 'Ener-G Pure Rice Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (106, 'Familia');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (107, 'Farina');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (108, 'Fiber 7 Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (109, 'Fiber One');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (110, 'Frankenberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (111, 'French Toast Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (112, 'Froot Loops');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (113, 'Frosted Flakes, Kellogg''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (114, 'Frosted Flakes, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (115, 'Frosted Fruit Rings');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (116, 'Frosted Mini Spooners, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (117, 'Frosted Mini Wheats');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (118, 'Frosted Shredded Wheat');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (119, 'Frosted Wheat Bites');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (120, 'Frosted cereal, with marshmallows');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (121, 'Frosted corn flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (122, 'Frosted flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (123, 'Frosted rice');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (124, 'Frosty O''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (125, 'Fruit & Fibre (fiber)');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (126, 'Fruit & Fibre (fiber) with Dates, Raisins and Walnuts');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (127, 'Fruit & Fibre (fiber) with Peaches, Raisins, Almonds, and Oat Clusters');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (128, 'Fruit Harvest');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (129, 'Fruit Harvest Apple Cinnamon');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (130, 'Fruit Harvest Strawberry Blueberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (131, 'Fruit Loops');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (132, 'Fruit Rings');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (133, 'Fruit Whirls');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (134, 'Fruit and Cream Oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (135, 'Fruity Dyno Bites, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (136, 'Fruity Pebbles');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (137, 'Golden Crisp');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (138, 'Golden Grahams');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (139, 'Golden Puffs, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (140, 'Granola');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (141, 'Granola, homemade');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (142, 'Granola, lowfat');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (143, 'Granola, lowfat, Kellogg''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (144, 'Granola, lowfat, with Raisins, Kellogg''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (145, 'Grape Nut O''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (146, 'Grape-Nuts');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (147, 'Grape-Nuts Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (148, 'Great Grains Crunchy Pecan Whole Grain Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (149, 'Great Grains, Raisins, Dates, and Pecans Whole Grain Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (150, 'Grits');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (151, 'Harina de maize con leche');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (152, 'Harmony Vanilla Almond Oats');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (153, 'Healthy Choice');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (154, 'Honey Bunches of Oat Honey Roasted');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (155, 'Honey Bunches of Oat with Strawberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (156, 'Honey Bunches of Oats');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (157, 'Honey Bunches of Oats with Almonds');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (158, 'Honey Buzzers, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (159, 'Honey Crisp Corn Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (160, 'Honey Crunch Corn Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (161, 'Honey Graham Squares, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (162, 'Honey Nut Clusters');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (163, 'Honey Nut Heaven');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (164, 'Honey Nut Shredded Wheat');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (165, 'Honey Smacks');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (166, 'Honeycomb');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (167, 'Honeycomb, strawberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (168, 'Instant Grits, all flavors');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (169, 'Jenny O''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (170, 'Just Right');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (171, 'Just Right with Fruit & Nut');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (172, 'Kaboom');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (173, 'Kasha');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (174, 'Kashi');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (175, 'Kashi GOLEAN');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (176, 'Kashi Good Friends');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (177, 'Kashi Good Friends Cinna-Raisin Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (178, 'Kashi Heart to Heart Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (179, 'Kashi Honey Puffed');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (180, 'Kashi Medley');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (181, 'Kashi Organic Promise');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (182, 'Kashi Pilaf');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (183, 'Kashi Pillows');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (184, 'Kashi Seven in the Morning');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (185, 'Kashi, Puffed');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (186, 'Kix');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (187, 'Kix, Berry Berry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (188, 'Life (plain and cinnamon)');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (189, 'Lucky Charms');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (190, 'Lucky Charms, Berry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (191, 'Lucky Charms, Chocolate');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (192, 'Magic Stars');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (193, 'Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (194, 'Malt-O-Meal, chocolate');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (195, 'Maltex');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (196, 'Marshmallow Mateys, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (197, 'Marshmallow Safari');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (198, 'Masa harina');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (199, 'Maypo');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (200, 'Millet');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (201, 'Millet, puffed');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (202, 'Mini-Wheats');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (203, 'Mini-Wheats Frosted Bite Size');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (204, 'Mini-Wheats Frosted Original');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (205, 'Mini-Wheats Frosted Raisin');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (206, 'Mini-Wheats Frosted Strawberry');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (207, 'Mother''s Natural Foods Cereal, Quaker');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (208, 'Muesli');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (209, 'Muesli(x)');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (210, 'Multigrain Oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (211, 'Multigrain cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (212, 'Natural Bran Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (213, 'Nature Valley Granola');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (214, 'Nature Valley Granola, with fruit and nuts');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (215, 'Nesquik');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (216, 'Nestum');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (217, 'Nu System Cuisine Toasted Grain Circles');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (218, 'Nutri-Grain');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (219, 'Nutri-Grain Golden Wheat and Raisin');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (220, 'Nutty Nuggets');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (221, 'Oat Bran Cereal, Quaker');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (222, 'Oat Bran Flakes, Health Valley');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (223, 'Oat bran cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (224, 'Oat bran uncooked');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (225, 'Oat cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (226, 'Oat flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (227, 'Oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (228, 'Oatmeal Crisp');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (229, 'Oatmeal Crisp with Almonds');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (230, 'Oatmeal Crisp, Apple Cinnamon');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (231, 'Oatmeal Crisp, Raisin');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (232, 'Oatmeal Squares');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (233, 'Oatmeal Swirlers');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (234, 'Oats, raw');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (235, 'Oh''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (236, 'Oh''s, Apple Cinnamon');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (237, 'Oh''s, Fruitangy');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (238, 'Oh''s, Honey Graham');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (239, 'Old Wessex Irish Style Oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (240, 'Optimum Slim, Nature''s Path');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (241, 'Optimum, Nature''s Path');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (242, 'Oreo O''s Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (243, 'Peanut Butter Toast Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (244, 'Polenta');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (245, 'Product 19');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (246, 'Puffed Rice, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (247, 'Puffed Wheat, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (248, 'Quaker Dinosaur Eggs oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (249, 'Quaker Fruit and Cream Oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (250, 'Quaker Instant Grits, all flavors');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (251, 'Quaker Multigrain Oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (252, 'Quaker Oatmeal Express');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (253, 'Quaker Oatmeal Nutrition for Women');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (254, 'Quaker Oatmeal Squares');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (255, 'Quisp');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (256, 'Raisin Bran Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (257, 'Raisin Bran, Kellogg''s');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (258, 'Raisin Bran, Post');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (259, 'Raisin Nut Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (260, 'Raisin bran (generic)');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (261, 'Reese''s Peanut Butter Puffs');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (262, 'Rice Krispies');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (263, 'Rice Krispies, Frosted');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (264, 'Rice Krispies, Treats Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (265, 'Rice bran, uncooked');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (266, 'Rice cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (267, 'Rice flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (268, 'Rice polishings');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (269, 'Rice, puffed');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (270, 'Roman Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (271, 'Seven-grain Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (272, 'Shredded Wheat');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (273, 'Shredded Wheat ''N Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (274, 'Shredded Wheat Spoon Size');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (275, 'Shredded Wheat, 100%');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (276, 'Shredded Wheat, Original');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (277, 'Smacks');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (278, 'Smart Start');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (279, 'Smorz');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (280, 'Special K');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (281, 'Special K Fruit & Yogurt');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (282, 'Special K Low Carb Lifestyle Protein Plus');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (283, 'Special K Red Berries');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (284, 'Special K Vanilla Almond');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (285, 'Strawberry Squares');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (286, 'Sun Country 100% Natural Granola, with Almonds');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (287, 'Sweet Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (288, 'Sweet Puffs');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (289, 'Tasteeos');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (290, 'Toasted Cinnamon Twists, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (291, 'Toasted Oatmeal Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (292, 'Toasted Oatmeal, Honey Nut');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (293, 'Toasted oat cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (294, 'Toasties');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (295, 'Toasty O''s, Apple Cinnamon, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (296, 'Toasty O''s, Honey and Nut, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (297, 'Toasty O''s, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (298, 'Tony''s Cinnamon Crunchers');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (299, 'Tootie Fruities, Malt-O-Meal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (300, 'Total');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (301, 'Total Brown Sugar & Oats');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (302, 'Total Corn Flakes');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (303, 'Total Instant Oatmeal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (304, 'Total Raisin Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (305, 'Trix');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (306, 'Trix, Reduced Sugar');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (307, 'Uncle Sam''s Hi Fiber Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (308, 'Under Cover Bears');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (309, 'Waffle Crisp');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (310, 'Weetabix Whole Wheat Cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (311, 'Wheat Hearts');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (312, 'Wheat bran, unprocessed (miller''s bran)');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (313, 'Wheat cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (314, 'Wheat germ');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (315, 'Wheat germ, with sugar and honey');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (316, 'Wheat, puffed');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (317, 'Wheat, puffed, presweetened with sugar');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (318, 'Wheatena');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (319, 'Wheaties');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (320, 'Wheaties Energy Crunch');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (321, 'Wheaties Raisin Bran');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (322, 'Whole wheat cereal');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (323, 'Whole wheat, cracked');
INSERT INTO adaptDB.cereal_list (cereal_id, name) VALUES (324, 'Zoom');
