ALTER TABLE
    `adaptdb`.`elements` ADD (width VARCHAR(255) DEFAULT '100%');

UPDATE adaptdb.elements SET name = '1.1', title = 'Height (ft)' where elements_id=118;
DELETE FROM adaptdb.elements WHERE elements_id IN (119, 120);
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, image_link, html, width) VALUES (119, 0, 0, '1.2', null, 'text', '(in)', 'left', 0, null, 'number', null, null, 15, 14, null, 0, null, null, 0, null, 1, 200, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, image_link, html, width) VALUES (120, 1, 0, '2', null, 'text', 'Weight(lbs)', 'left', 0, null, 'number', null, null, 15, 14, null, 0, null, null, 0, null, 1, 200, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, image_link, html, width) VALUES (210, 1, 0, '3', null, 'text', 'Age', 'left', 0, null, 'number', null, null, 15, 14, null, 0, null, null, 0, null, 1, 200, null, 0, null, null, null, null, '20em');

UPDATE adaptdb.elements SET width = '20em' WHERE type = 'text';

UPDATE adaptdb.elements SET width = '40em' WHERE elements_id = 80;


INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '3.2', '{3} = ''yes'' and {3.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 25, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '6.2', '{6} = ''yes'' and {6.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 26, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '8.2', '{8} = ''yes'' and {8.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 27, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '9.2', '{9} = ''yes'' and {9.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 27, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '10.2', '{10} = ''yes'' and {10.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 28, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '11.2', '{11} = ''yes'' and {11.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 28, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '12.2', '{12} = ''yes'' and {12.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 28, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '13.2', '{13} = ''yes'' and {13.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 29, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '14.2', '{14} = ''yes'' and {14.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 29, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '15.2', '{15} = ''yes'' and {15.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 29, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '16.2', '{16} = ''yes'' and {16.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 30, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '17.2', '{17} = ''yes'' and {17.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 30, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '18.2', '{18} = ''yes'' and {19.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 30, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '19.2', '{19} = ''yes'' and {19.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 31, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '20.2', '{20} = ''yes'' and {20.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 31, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '21.2', '{21} = ''yes'' and {21.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 31, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '22.2', '{22} = ''yes'' and {22.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 32, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '23.2', '{23} = ''yes'' and {23.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 32, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '24.2', '{24} = ''yes'' and {24.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 32, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '25.2', '{25} = ''yes'' and {25.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 33, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '26.2', '{26} = ''yes'' and {26.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 33, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '27.2', '{27} = ''yes'' and {27.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 33, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '28.2', '{28} = ''yes'' and {28.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 34, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '29.2', '{29} = ''yes'' and {29.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 34, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');
INSERT INTO adaptdb.elements (elements_id, start_with_new_line, has_other, name, visible_if, type, title, title_location, col_count, description, input_type, other_text, popupdescription, page_id, questionnaires_id, choices_by_url, is_required, enable_if, render_as, is_all_row_required, default_value, min, max, required_if, indent, image_height, image_width, html, image_link, width) VALUES ((SELECT MAX( elements_id ) from adaptdb.elements e)+1, 1, 0, '30.2', '{30} = ''yes'' and {30.1} notempty', 'dropdown', 'Enter how many times?', 'left', 0, null, null, null, null, 34, 16, 'http://localhost:8080/api/adapt/questionnaire/countList', 0, null, 'select2', 0, null, 0, 0, null, 0, null, null, null, null, '20em');

update adaptdb.elements set choices_by_url = 'http://localhost:8080/api/adapt/questionnaire/medicine' where choices_by_url='http://localhost:8080/api/adapt/questionnaire/countList';
